apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1

  selector:
    matchLabels:
      app: user-service

  template:
    metadata:
      labels:
        app: user-service

    spec:
      containers:
        - name: user-service
          image: api-gateway-user-service:latest
          imagePullPolicy: Never

          ports:
            - containerPort: 8080

          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker

            - name: DB_URL
              value: jdbc:postgresql://host.docker.internal:5432/user_service_db

            - name: DB_USERNAME
              value: postgres

            - name: DB_PASSWORD
              value: postgres

            - name: REDIS_HOST
              value: host.docker.internal

            - name: REDIS_PORT
              value: "6379"

            - name: JWT_SECRET
              value: superSecretKeyThatIsLongEnoughForJwt123456789

          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            failureThreshold: 30
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5